- shell:
  -
    description: Moving old bashrc
    command: FILE="$HOME/.bashrc"; if [[ -e "$FILE" ]] && [[ ! -L "$FILE" ]]; then mv "$FILE" "${FILE}.asinstalled"; else echo "$FILE doesn't exist or exists as a link, not moving, no error" >&2; fi

- link:
    ~/.config/git/config: git/gitconfig
    ~/.config/git/workconfig: git/workconfig
    ~/.config/git/personalconfig: git/personalconfig
    ~/.bashrc: bash/bash.sh
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux.reset.conf: tmux/tmux.reset.conf
    ~/.ssh/config: ssh/config

- shell:
  -
    description: Fix ssh config file permissions
    command: chmod 600 ssh/config
  -
    description: Install required packages
    command: scripts/install.sh
