- link:
    ~/.vimrc: vim/vimrc
    ~/.vim: vim/vim
    ~/.config/nvim/init.vim: vim/nvim/init.vim
    ~/.config/nvim/coc-settings.json: config/coc-settings.json
- shell:
  -
    description: Install required packages
    command: scripts/install_nvim.sh
